---
stages:
    # - build
    - tests

'TODO registrar':
    stage: tests
    interruptible: false
    allow_failure: true
    before_script:
        - curl -sL "https://gitlab.com/aeliot-tm/gitlab-control/-/raw/main/controller.sh" -o ./gitlab-control
        - chmod +x ./gitlab-control
    script:
        - export NEW_BRANCH=$(./gitlab-control generate_name 'todo-registrar-{random:8}')
        - "[ 1 -eq $(./gitlab-control branch_exists \"$NEW_BRANCH\") ] && echo 'Skipping: branch already exists' && exit 0"
        - "[ 1 -eq $(./gitlab-control check_opened \"$NEW_BRANCH\" \"development\" --like 'todo-registrar-*') ] && echo 'Skipping: opened MR exists' && exit 0"
        - echo "NO opened MR exists! Looking for new TODOs..."
        - ./gitlab-control checkout "$NEW_BRANCH"
        - |
            docker run --rm \
                -v "$(pwd):/code" \
                -e GITLAB_PERSONAL_ACCESS_TOKEN \
                -e GITLAB_PROJECT_IDENTIFIER \
                ghcr.io/aeliot-tm/todo-registrar:latest --config=.todo-registrar.yaml
        - |
            if ./gitlab-control commit "TODO-REGISTRAR: automated registering of new TODOs"; then
                ./gitlab-control push "$NEW_BRANCH"
                ./gitlab-control create_mr --target "development" --title "TODO-REGISTRAR: automated registering of new TODOs"
            else
                echo "No changes, nothing to commit & push!"
            fi
    rules:
        - if: $CI_COMMIT_BRANCH == "development"
