---
stages:
  # - build
  - tests

'TODO registrar':
  stage: tests
  allow_failure: true
  interruptible: false
  before_script:
    - command -v jq >/dev/null || (apt-get update -qq && apt-get install -y -qq jq)
    - curl -fsSL "$GITLAB_CONTROL_SCRIPT_URL" -o ./gitlab-control && chmod +x ./gitlab-control
    - curl -fsSL "$BUILD_MR_BOBY_SCRIPT_URL" -o ./scripts/build-mr-body.sh && chmod +x ./scripts/build-mr-body.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
  script:
    - export RUNNER_TEMP="/tmp/todo-registrar-${CI_PIPELINE_ID}"
    - mkdir -p "$RUNNER_TEMP"
    - export NEW_BRANCH=$(./gitlab-control generate_name 'todo-registrar-{random:8}')
    - "[ 1 -eq $(./gitlab-control branch_exists \"$NEW_BRANCH\") ] && echo 'Skipping: branch already exists' && exit 0"
    - "[ 1 -eq $(./gitlab-control check_opened \"$NEW_BRANCH\" \"development\" --like 'todo-registrar-*') ] && echo 'Skipping: opened MR exists' && exit 0"
    - echo "NO opened MR exists! Looking for new TODOs..."
    - ./gitlab-control checkout "$NEW_BRANCH"
    - |
      docker run --rm \
          -v "$(pwd):/code" \
          -v "${RUNNER_TEMP}:/runner-temp" \
          -e GITLAB_PERSONAL_ACCESS_TOKEN \
          -e GITLAB_PROJECT_IDENTIFIER \
          ghcr.io/aeliot-tm/todo-registrar:latest \
          --config=.todo-registrar.yaml \
          --report-format=json --report-path=/runner-temp/todo-registrar-report.json
    - |
      if ./gitlab-control commit "TODO-REGISTRAR: automated registering of new TODOs"; then
          ./gitlab-control push "$NEW_BRANCH"
          REPORT_PATH="${RUNNER_TEMP}/todo-registrar-report.json"
          MR_BODY_PATH="${RUNNER_TEMP}/mr-body.md"
          ./scripts/build-mr-body.sh "$REPORT_PATH" "$MR_BODY_PATH"
          ./gitlab-control create_mr \
              --target "development" \
              --title "TODO-REGISTRAR: automated registering of new TODOs" \
              --description "$(cat "$MR_BODY_PATH")"
          ./gitlab-control trigger_pipeline "$NEW_BRANCH"
      else
          echo "No changes, nothing to commit & push!"
      fi
  variables:
    BUILD_MR_BOBY_SCRIPT_URL: https://raw.githubusercontent.com/Aeliot-Tm/todo-registrar/refs/tags/4.2.0/examples/GitLab/scripts/build-mr-body.sh
    GITLAB_CONTROL_SCRIPT_URL: https://gitlab.com/aeliot-tm/gitlab-control/-/raw/0.2.0/controller.sh

'TODO Registrar: statistic':
  stage: test
  allow_failure: true
  interruptible: true
  before_script:
    - command -v jq >/dev/null || (apt-get update -qq && apt-get install -y -qq jq)
    - mkdir -p "$(dirname "$GITLAB_CONTROL")"
    - curl -fsSL "$GITLAB_CONTROL_SCRIPT_URL" -o "$GITLAB_CONTROL" && chmod +x "$GITLAB_CONTROL"
    - curl -fsSL "h$BUILD_MR_COMMENT_SCRIPT_URL" -o "$BUILD_MR_COMMENT_SCRIPT" && chmod +x "$BUILD_MR_COMMENT_SCRIPT"
    - curl -fsSL "$POST_MR_STATISTIC_SCRIPT_URL" -o "$POST_MR_STATISTIC_SCRIPT" && chmod +x "$POST_MR_STATISTIC_SCRIPT"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - export RUNNER_TEMP="/tmp/todo-registrar-statistic-${CI_PIPELINE_ID}"
    - mkdir -p "$RUNNER_TEMP"
    - |
      docker run --rm \
        -v "$(pwd)/app:/code" \
        -v "${RUNNER_TEMP}:/runner-temp" \
        ghcr.io/aeliot-tm/todo-registrar:latest \
        --dry-run \
        --config=.todo-registrar-statistic.yaml \
        --report-format=json --report-path=/runner-temp/todo-registrar-report.json
    - '"$POST_MR_STATISTIC_SCRIPT" "${RUNNER_TEMP}/todo-registrar-report.json"'
  variables:
    BUILD_MR_COMMENT_SCRIPT: "${CI_PROJECT_DIR}/.ci/build-mr-comment.sh"
    BUILD_MR_COMMENT_SCRIPT_URL: https://raw.githubusercontent.com/Aeliot-Tm/todo-registrar/refs/tags/4.2.0/bin/build-mr-comment.sh
    GITLAB_CONTROL: "${CI_PROJECT_DIR}/.ci/gitlab-control"
    GITLAB_CONTROL_SCRIPT_URL: https://gitlab.com/aeliot-tm/gitlab-control/-/raw/0.2.0/controller.sh
    POST_MR_STATISTIC_SCRIPT: "${CI_PROJECT_DIR}/.ci/post-mr-statistic-comment.sh"
    POST_MR_STATISTIC_SCRIPT_URL: https://raw.githubusercontent.com/Aeliot-Tm/todo-registrar/refs/tags/4.2.0/bin/post-mr-statistic-comment.sh
