# This file is part of the TODO Registrar project.
#
# (c) Anatoliy Melnikov <5785276@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.

paths:
  in: ../../src/Service/Registrar/GitLab

registrar:
  type: GitLab
  options:
    issue:
      addTagToLabels: true
      assignees:
        - username1
        - username2
      labels:
        - tech-debt
        - Label-2
      tagPrefix: tag-
      milestone: 123  # optional
      due_date: '2025-12-31'  # optional, format: YYYY-MM-DD
    service:
      # Replace with your actual token (or set GITLAB_PERSONAL_ACCESS_TOKEN environment variable)
      personalAccessToken: null
      # Or define oauthToken for OAuth type of authentication
      # oauthToken: null  # (or set GITLAB_OAUTH_TOKEN environment variable)
      host: https://gitlab.com  # optional, for self-hosted (default: https://gitlab.com)
      # Use either <project id> (more efficient) or <project path> (more readable)
      # Replace with your actual project identifier (or set GITLAB_PROJECT_IDENTIFIER environment variable)
      project: null

tags:
  - todo
  - fixme
  - a_custom_tag

