# This file is part of the TODO Registrar project.
#
# (c) Anatoliy Melnikov <5785276@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.

paths:
  in: .

registrar:
  type: GitHub
  options:
    issue:
      addTagToLabels: true
      labels:
        - Label-1
        - Label-2
      tagPrefix: tag-
    service:
      # Replace with your actual token (or set GITHUB_PERSONAL_ACCESS_TOKEN environment variable)
      personalAccessToken: '%env(GITHUB_PERSONAL_ACCESS_TOKEN)%'
      owner: Aeliot-Tm
      repository: todo-registrar

tags:
  - todo
  - fixme
  - a_custom_tag

