paths:
  in: /app/src
  exclude:
    - vendor
    - var
    - tests

registrar:
  type: YandexTracker
  options:
    issue:
      queue: MYQUEUE
      type: task
      priority: normal
      assignee: developer.login
      addTagToLabels: true
      labels:
        - tech-debt
        - from-code
      tagPrefix: ''
    service:
      isCloud: '%env(YANDEX_TRACKER_IS_CLOUD)%'
      orgId: '%env(YANDEX_TRACKER_ORG_ID)%'
      token: '%env(YANDEX_TRACKER_TOKEN)%'

tags:
  - todo
  - fixme

