name: Prepare Opened Issue

on:
  issues:
    types: [ opened ]

jobs:
  prepare-issue:
    name: Prepare Issue
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        if: 1 == 0 # forbid the step temporary
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ secrets.GH_TODO_REGISTRAR_PROJECT_URL }}
          github-token: ${{ secrets.GH_ADD_PROJECT_TOKEN }}
