name: Prepare Issue

on:
  issues:
    types: [ opened ]

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare-issue:
    name: Prepare Issue
    runs-on: ubuntu-latest

    # Define the permissions for the action
    permissions:
      issues: write
      repository-projects: write

    steps:

      - name: Add Project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TODO_REGISTRAR_ACCESS_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-project "${{ secrets.GH_TODO_REGISTRAR_PROJECT }}"
