name: Security Audit

on:
  push:
  schedule:
    - cron: '45 12 * * *'

permissions:
  contents: read

jobs:
  composer-audit:
    name: 'Composer Security Vulnerabilities Audit'
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
          coverage: none

      - uses: actions/checkout@v4

      - name: 'Check security vulnerabilities'
        run: composer audit --locked
