name: TODO in PR Statistic

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  statistic:
    uses: Aeliot-Tm/todo-registrar-statistic-action/.github/workflows/statistic.yaml@399d98ab89d662901bede273f25094f56109e096
    with:
      config: |
        paths:
          in: .
          append: bin/todo-registrar
          exclude:
            - tests/fixtures
            - var
            - vendor
        process:
          glueSameTickets: true
          glueSequentialComments: true
        registrar:
          type: DryRun
        tags:
          - todo
          - fixme
