name: TODO Registrar

on:
  push:
    branches: [ "*" ]

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  todo-registrar:
    name: Register TODO
    runs-on: ubuntu-latest

    # Define the permissions for the action
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Register TODOs
        uses: Aeliot-Tm/todo-registrar-action@1.6.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TODO_REGISTRAR_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          config: |
            paths:
              in: .
              append: bin/todo-registrar
              exclude:
                - tests/fixtures
                - var
                - vendor

            registrar:
              type: GitHub
              options:
                issue:
                  addTagToLabels: true
                  labels:
                    - tech-debt
                  tagPrefix: tag-
                  showContext: numbered
                  contextTitle: "## Added in position:"
                service:
                  personalAccessToken: "%env(GH_PERSONAL_ACCESS_TOKEN)%"
                  repository: "%env(GITHUB_REPOSITORY)%"

            tags:
              - todo
              - fixme
          env_vars: |
            GH_PERSONAL_ACCESS_TOKEN
            GITHUB_REPOSITORY
          new_branch_name: 'todo-registrar'
